UI_Arlequin_Double_Gun_Dynamics: "Подвійна гармата: Динаміка"
UI_Arlequin_Double_Gun_HP: "Подвійна гармата: ХП"
UI_Arlequin_Double_Gun_Speed_Mobility: "Подвійна гармата: Швидкість Мобільність"
UI_Arlequin_HE_Dynamics: "Фугас Динаміка"
UI_Arlequin_HE_HP: "Фугас ХП"
UI_Arlequin_HE_Speed_Mobility: "Фугас: Швидкість Мобільність"
UI_Arlequin_Machine_Gun_Dynamics: "Кулемет: Динамікаs"
UI_Arlequin_Machine_Gun_HP: "Кулемет: ХП"
UI_Arlequin_Machine_Gun_Speed_Mobility: "Кулемет: Швидкість Мобільність"
UI_Arlequin_description: "Arlequin bis [Франція]"
UI_BaiLang_DPM_Rotation: "ДПМ: Швидкість оберту"
UI_BaiLang_description: "Bai Lang A [Китай]"
UI_Beowulf_DPM_Rotation: "ДПМ: Швидкість оберту"
UI_Beowulf_description: "Beowulf S1 [Швеція]"
UI_Harbinger_Autoreloader_Armor: "Дозаряджання: Броня"
UI_Harbinger_Autoreloader_Mobility: "Дозаряджання: Мобільність"
UI_Harbinger_Autoreloader_Rotation: "Дозаряджання: Швидкість оберту"
UI_Harbinger_Autoreloader_Speed_Mobility: "Дозаряджання: Швидкість Мобільність"
UI_Harbinger_DPM_Armor: "ДПМ: Броня"
UI_Harbinger_DPM_Mobility: "ДПМ: Мобільність"
UI_Harbinger_DPM_Rotation: "ДПМ: Швидкість оберту"
UI_Harbinger_DPS_Armor: "ДПС: Броня"
UI_Harbinger_DPS_Loading_Mobility: "ДПС - Швидкість заряджання - Мобільність"
UI_Harbinger_DPS_Mobility: "ДПС - Динаміка - Мобільність"
UI_Harbinger_DPS_Speed_Mobility: "ДПС - Швидкість - Мобільність"
UI_Harbinger_description: "Harbinger Mk. V [U.K]"
UI_Huragan_DPM_Rotation_6: "ДПМ макс.Броня 6-снарядів"
UI_Huragan_DPM_Rotation_8: "ДПМ Швидкість оберту 8-снарядів"
UI_Huragan_DPS_Mobility_6: "ДПС Мобільність 6-снарядів"
UI_Huragan_DPS_Mobility_8: "ДПС Мобільність 8-снарядів"
UI_Huragan_Daki: "Daki Huragan"
UI_Huragan_description: "Huragan CS [Польща]"
UI_Raven_DPM_Armor: "ДПМ: Броня"
UI_Raven_DPM_Mobility: "ДПМ: Мобільність"
UI_Raven_DPM_Rotation: "ДПМ: Швидкість оберту"
UI_Raven_DPS_Armor: "ДПС: Броня"
UI_Raven_DPS_Mobility: "ДПС Мобільність"
UI_Raven_DPS_Speed_Mobility: "ДПС Швидкість Мобільність"
UI_Raven_Daki: "Daki Raven"
UI_Raven_Magazine_Armor: "Магазин заряджання: Броня"
UI_Raven_Magazine_Mobility: "Магазин заряджання: Мобільність"
UI_Raven_Magazine_Rotation: "Магазин заряджання: Швидкість оберту"
UI_Raven_Magazine_Speed_Mobility: "Магазин заряджання: Швидкість Мобільність"
UI_Raven_description: "Raven [США]"
UI_Varyag_DPM_Armor: "ДПМ: Броня"
UI_Varyag_DPM_HP: "ДПМ: ХП"
UI_Varyag_DPS_Armor: "ДПС: Броня"
UI_Varyag_DPS_HP: "ДПС ХП"
UI_Varyag_Double_Gun_Armor: "Два стволи: Броня"
UI_Varyag_Double_Gun_HP: "Два стволи: ХП"
UI_Varyag_description: "Varyag the Speedster [срср]"
UI_Walkure_DPM_Armor: "ДПМ: Броня"
UI_Walkure_DPM_HP: "ДПМ: ХП"
UI_Walkure_DPS_Armor: "ДПС: Броня"
UI_Walkure_DPS_HP: "ДПС: ХП"
UI_Walkure_Machine_Gun_Armor: "Кулемет: Броня"
UI_Walkure_Machine_Gun_HP: "Кулемет: ХП"
UI_Walkure_Machine_Gun_HP_Armor: "Кулемет: ХП Броня"
UI_Walkure_description: "Walküre KPz [Німеччина]"
UI_description: "Помічник сталевого мисливця"
UI_setting_autoUpgrade_custom: "Спеціальна конфігурація автоматичної модернізації"
UI_setting_autoUpgrade_disabled: "Автоматична модернізація вимкнена"
UI_setting_autoUpgrade_text: "Автоматична модернізація техніки в боях Сталевого Мисливця"
UI_setting_autoUpgrade_tooltip: ""
UI_setting_customCfg_text: "Користувальницький конфіг модернізації"
UI_setting_customCfg_tooltip: "Список модернізації. Він повинен містити 6 чисел, кожне з яких відокремлене комою, інакше він буде проігнорований і автоматична модернізація буде вимкнена! Перше число у списку - це бажана модернізація для 2 рівня, друге число - бажана модернізація для 3 рівня, і т. інш. Коли справа доходить до бажаної модернізації для максимального 7-го рівня, зверніть увагу, що є три варіанти, з яких одночасно можна вибрати лише 2. Залежно від того, яку модернізацію було обрано на 6 рівні. За необхідності, подивіться на дерево досліджень відповідної техніки. В кінці списку не обов'язково ставити кому.\n\n<b>Інформація:</b>\n<b>Користувальницький конфіг модернізації</b> повинен бути обраний для відповідної техніки, перш ніж цей список стане активним!\n\nПриклад: 2,1,2,1,2,3"
UI_setting_labelBattle_text: "===[ Налаштування бою ]========================"
UI_setting_labelGeneral_text: "===[ Інформація та загальні налаштування ]================"
UI_setting_labelUprade_text: "===[ Налаштування модернізації ]======================="
UI_setting_remove3DLootMode_ready: "Коли радар готовий"
UI_setting_remove3DLootMode_scan: "З радіолокаційним скануванням"
UI_setting_remove3DLootMode_text: "Прибрати 3D маркери луту"
UI_setting_showLoot3D_text: "Показати 3D маркери луту, після натискання кнопки Радару"
UI_setting_showLoot3D_tooltip: ""
UI_setting_tooltipInfo_text: "На рівні 7 ви можете вибрати лише 2 варіанти на основі вашого попереднього вибору на рівні 6"
