IGM_deadShot_blocked: "Стрілянину по трупах заблоковано!"
IGM_locked: "заблоковано"
IGM_moveMe: "drag & drop!"
IGM_override_activated: "Обхід Safe Shot Pro активовано!"
IGM_override_deactivated: "Обхід Safe Shot Pro деактивовано!"
IGM_safeshotGUI: "Графічний інтерфейс Safe Shot Pro тепер %s."
IGM_teamShot_blocked: "Командний постріл заблоковано!"
IGM_unlocked: "розблоковано"
IGM_wasteShot_blocked: "Промах заблоковано!"
IGM_welcomeMessage: "Safe Shot Pro активовано"
UI_description: "Safe Shot Pro"
UI_setting_blockDeadShot_text: "Блокувати постріли по знищених танках"
UI_setting_blockDeadShot_tooltip: "Увімкнути/вимкнути блокування пострілів по вже знищених танках"
UI_setting_blockTeamKillerShot_text: "Блокувати постріли по командоубивцях"
UI_setting_blockTeamKillerShot_tooltip: "Увімкнути/вимкнути блокування пострілів по кілеру команди (синій нік)"
UI_setting_blockTeamShot_text: "Блокувати постріли по товаришах по команді"
UI_setting_blockTeamShot_tooltip: "Вмикає/вимикає блокування пострілів по товаришах по команді".
UI_setting_blockWasteShot_text: "Блокувати постріли без цілі"
UI_setting_blockWasteShot_tooltip: "Вмикає/вимикає блокування пострілів за відсутності цілі".
UI_setting_blockedShotMessage_text: "Сповіщення про заблокований постріл"
UI_setting_blockedShotMessage_tooltip: "Вмикає/вимикає сповіщення, якщо постріл заблоковано".
UI_setting_blockingTarget_text: "Введіть повідомлення для "Блокування цілі"
UI_setting_blockingTarget_tooltip: "Тут ви можете ввести повідомлення, яке буде надіслано в бойовий чат, коли хтось заблокує вашу ціль<br/><br/>Placeholder:><br/>{blockername} - вставить нікнейм гравця, який блокує вашу ціль.<br/>{blockertank} - вставить назву танка, який блокує вашу ціль.<br/><br/>Примітка:Це повідомлення має бути англійською мовою, щоб його могла прочитати вся ваша команда."
UI_setting_hotkeyOverride_text: "Гаряча клавіша: Обійти захист від пострілу"
UI_setting_hotkeyOverride_tooltip: "Тут ви можете визначити гарячу клавішу, яка дозволить вам вимкнути функцію безпечного пострілу, якщо утримувати її натиснутою."
UI_setting_hotkeyTogglePanelLock_text: "Гаряча клавіша: Блокування панелі перемикачів"
UI_setting_hotkeyTogglePanelLock_tooltip: "Блокування/розблокування панелі. Ви можете переміщати її перетягуванням!"
UI_setting_image_text: "Виберіть зображення екіпажу"
UI_setting_image_tooltip: "Виберіть 0, щоб вимкнути зображення екіпажу.<br/>за замовчуванням: 1"
UI_setting_labelGeneral_text: "===[ ІНФОРМАЦІЯ ТА ЗАГАЛЬНІ НАЛАШТУВАННЯ ]======================="
UI_setting_language_file: "Автор мовного файлу"
UI_setting_language_file_author: "Soul4Life"
UI_setting_sendTeamMessage_text: "Надіслати повідомлення про блокування"
UI_setting_sendTeamMessage_tooltip: "Вмикає/вимикає надсилання повідомлення в командний чат, якщо хтось блокує вашу ціль."
UI_setting_timeDeadShotBlock_text: "Час блокування біля знищених танків"
UI_setting_timeDeadShotBlock_tooltip: "Час (секунди), протягом якого блокується постріл по транспортному засобу після його знищення.<br/><br/>Note: This options is only active when 'Block shots on destroyed tanks' is activated."
