name: Deploy to R2

on:
  push:
    branches: [ "main" ]  # Або "master", залежно від репозиторію

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true  # <--- Це важливо!

      - name: Install rclone
        run: sudo apt-get update && sudo apt-get install -y rclone

      - name: Configure rclone for R2
        env:
          ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY_ID }}
          SECRET_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.R2_REGION }}
          ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
        run: |
          mkdir -p ~/.config/rclone
          echo "[R2]" > ~/.config/rclone/rclone.conf
          echo "type = s3" >> ~/.config/rclone/rclone.conf
          echo "provider = Cloudflare" >> ~/.config/rclone/rclone.conf
          echo "access_key_id = $ACCESS_KEY" >> ~/.config/rclone/rclone.conf
          echo "secret_access_key = $SECRET_KEY" >> ~/.config/rclone/rclone.conf
          echo "region = $REGION" >> ~/.config/rclone/rclone.conf
          echo "endpoint = $ENDPOINT" >> ~/.config/rclone/rclone.conf

      - name: Sync files to R2 Bucket
        env:
          BUCKET: ${{ secrets.R2_BUCKET }}
        run: |
          rclone sync . R2:$BUCKET --exclude ".git/**" --progress
